vich_uploader:
    db_driver: orm

    mappings:
        users_pictures:
            uri_prefix: '%profile_pictures%'
            upload_destination: '%kernel.project_dir%/public%profile_pictures%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false